housingsearch/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
app_name = ''
urlpatterns = [
    path('', views.index, name='index'),
    path('housing/<int:housing_id>/', views.housing_detail_view, name='detail'),
    path('housing/<int:housing_id>/rate/', views.rate, name='rate'),
    path('home/', views.HomePageView.as_view(), name='home'),
    path('accounts/login', views.HousingLogoutView.as_view(), name='logout'),
    path('home/advice/', views.housing_advice_view.as_view(), name='advice'),
    path('home/saveAdvice', views.saveAdvice, name='save_advice'),
    path('home/advicePost', views.advice, name='advice_post'),
    path('home/roommatefinder/', views.PostList.as_view(), name='roommatefinder'),
    path('map/', views.MapView.as_view(), name='map'),
    path('profile/', views.profile_view, name='profile'),
    path('editprofile/', views.edit_profile_view, name='editprofile'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('home/post', views.make_post, name='make_post')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

offgrounds/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('housingsearch.urls')),
    path('housingsearch/', include('housingsearch.urls')),
    path('accounts/', include('allauth.urls')),
]

housingsearch/models.py
from django.db import models
from django.contrib import admin
import geocoder
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
import datetime
from django.db import models
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils.text import slugify

access_token = 'pk.eyJ1IjoiZ2F2aW4tZ3VvIiwiYSI6ImNrdm9iZXozaGN3MXoycHQ5am5vOTIzajMifQ.gycEz65lfHwNqvAqZPjQhA'
class Housing(models.Model):
    address = models.CharField(max_length=3000)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    rent = models.IntegerField()
    bed = models.IntegerField()
    bath = models.IntegerField()
    sqft = models.IntegerField()
    image = models.ImageField(upload_to='housing')
    def save(self, *args, **kwargs):
        g = geocoder.mapbox(self.address, key=access_token)
        g = g.latlng
        self.lat = g[0]
        self.long = g[1]
        return super(Housing, self).save(*args, **kwargs)

class Rating(models.Model):
    housing = models.ForeignKey(Housing, on_delete=models.CASCADE)
    rate_text = models.CharField(max_length=200)
    rate = models.IntegerField(default=0)
    #review_text = models.CharField(max_length=300, default='')

class Review(models.Model):
    name = models.CharField(max_length=300, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    housing = models.ForeignKey(Housing, on_delete=models.CASCADE)
    review_text = models.CharField(max_length=300, null=True)

class Profile(models.Model):
    username = models.CharField(max_length=300, null=False, primary_key=True, unique=True, default=" ")
    age = models.CharField(max_length=3, null=True, default=" ")
    gender = models.CharField(max_length=300, null=True, default=" ")
    school_year = models.CharField(max_length=300,null=True,default=" ")
    #USERNAME_FIELD = 'username'
    # @receiver(post_save, sender=User)  # add this
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         Profile.objects.create(user=instance)
    #
    # @receiver(post_save, sender=User)  # add this
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.profile.save()

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(
        default='',
        editable=True,
        max_length=300,
        unique=True
    )
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=1)
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
class AdvicePost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return self.title

housingsearch/forms.py
from .models import Comment, Post
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content',)

housingsearch/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.contrib.auth.views import LogoutView
from django.views.generic import CreateView
from django.contrib.auth.models import User
from .models import Housing, Rating, Review, Profile, Post, AdvicePost
from django.utils import timezone
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import CommentForm, PostForm

def index(request):
    return HttpResponseRedirect('home')

class HomePageView(generic.ListView):
    #model = Housing
    template_name = "home.html"
    context_object_name = "housing_set"
    def get_queryset(self):
        return Housing.objects.all()

class HousingLogoutView(LogoutView):
    template_name = 'home.html'

class housing_advice_view(generic.ListView):
    template_name = 'advice.html'
    context_object_name = 'advice_list'

    def get_queryset(self):
        return AdvicePost.objects.all()

def advice(request):
    return render(request, 'make_advice.html')

# Form handler
def saveAdvice(request):
    selected_title = request.POST.get('title',"")
    selected_body = request.POST.get('body',"")
    if (not selected_title or not selected_body):
        return render(request, 'advice.html', {'error_message': "You didn't input a title and/or the text"})
    else:
        advice = AdvicePost(title=selected_title,body=selected_body)
        advice.save()
        return HttpResponseRedirect(reverse('advice'))
# DELETE THIS AND REPLACE WITH CLASS
def roommate_finder_view(request):
    return render(request, 'roommate.html')

# class HousingDetailView(generic.DetailView):
#     model = Housing
#     template_name = 'detail.html'
#     def get_queryset(self):
#         return Housing.objects.all()

def housing_detail_view(request, housing_id):
    housing = get_object_or_404(Housing, pk=housing_id)
    #queryset_profile = Profile.objects.filter(username=request.user.username)
    #profile = get_object_or_404(queryset_profile)
    #review = None
    # new_review = None
    # if request.method == 'POST':
    #     review = Review(data=request.POST)
    #     print(review)
    #     if review.is_valid():
    #         # Create Post object but don't save to database yet
    #         new_review = review.save(commit=False)
    #         new_review.name = request.user
    #         print(new_review)
    #         print(new_review.name)
    #         # Save the post to the database
    #         new_review.save()
    #print(Rating.objects.filter(housing_id=housing_id))
    rating = Rating.objects.filter(housing_id=housing_id)
    #review = Review.objects.filter(housing_id=housing_id)
    #print(Review.objects.filter(housing_id=housing_id))
    average = 0
    count = 0
    #profile = Profile.objects.get(username=request.user.username)
    for r in rating:
        count += r.rate
        average += int(r.rate_text) * r.rate
        #print(r.review_text)
    average /= count if count != 0 else 1
    average = float('%.3g' % average)
    #print(average)
    #review = rate_and_review.review_text
    return render(request, 'detail.html', {'housing':housing, 'rating': rating, 'average': average})

def rate(request, housing_id):
    housing = get_object_or_404(Housing, pk=housing_id)
    #review = get_object_or_404(Review, pk=housing_id)
    print("request.post", request.POST)
    try:
        selected_rate = housing.rating_set.get(pk=request.POST['choice'])
        #print("selected rate", selected_rate)
        review = Review()
        review.review_text = request.POST['review']
        review.name = request.user.username
        review.housing_id = housing_id
        #print(review, review.review_text, review.pk)
        review.save()
       # print(selected_rate.review_text)
    except (KeyError, Rating.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'housing': housing,
            'error_message': "You didn't select a rating.",
        })
    else:
        selected_rate.rate += 1
        selected_rate.save()

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('detail', args=(housing.id,)))


class MapView(CreateView):
    model = Housing
    fields = ['address']
    template_name = 'map.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['addresses'] = Housing.objects.all()
        return context


def profile_view(request):
    #profile = get_object_or_404(Profile)

    if not Profile.objects.filter(username=request.user.username):
        profile = Profile()
        name = request.user.username
        profile.username = name
        profile.save()
    # if request.method == "POST":
    #     profile.age = request.POST['age']
    #     profile.gender = request.POST['gender']
    #     profile.save()
        return render(request, 'profile.html',{'profile': profile})
    else:
        queryset = Profile.objects.filter(username=request.user.username)
        profile = get_object_or_404(queryset)
        return render(request, 'profile.html', {'profile': profile})

def edit_profile_view(request):
    print(request.user)
    queryset = Profile.objects.filter(username=request.user.username)
    profile = get_object_or_404(queryset)
    print(profile)
    # profile = Profile()
    # name = request.user.username
    # profile.username = name
    if request.method == "POST":
        if request.POST['age'] :
            print(request.POST)
            profile.age = request.POST['age']

            print(request.POST)
            print(profile.age)


            profile.save()
        if request.POST['gender'] != "Choose...":
            profile.gender = request.POST['gender']
            print(profile.gender)
            profile.save()

        if request.POST['school_year'] != "Choose...":
            profile.school_year = request.POST['school_year']
            print(profile.school_year)
            profile.save()
        return HttpResponseRedirect('/profile')
    return render(request, 'editprofile.html',{'profile': profile})

class PostList(generic.ListView):
    """
    Return all posts that are with status 1 (published) and order from the latest one.
    """
    queryset = Post.objects.filter(status=1).order_by('-created_at')
    template_name = 'index.html'

def post_detail(request, slug):
    template_name = 'post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment

            new_comment.post = post
            new_comment.name = request.user
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

def make_post(request):
    template_name = 'make_post.html'
    new_post = None
    
    if request.method == 'POST':
        post_form = PostForm(data=request.POST)
        #print(post_form)
        if post_form.is_valid():
            # Create Post object but don't save to database yet
            new_post = post_form.save(commit=False)
            new_post.author = request.user
            # Save the post to the database
            new_post.save()
    else:
        post_form = PostForm()

    return render(request, template_name, {'new_post': new_post,
                                           'post_form': post_form})



#Citations for HTMLs:
#https://getbootstrap.com/docs/5.1/examples/
#https://getbootstrap.com/docs/5.1/getting-started/introduction/
#Postgres: https://stackoverflow.com/questions/46416877/duplicate-key-issue-when-loading-back-json-file-postgresql,
#https://medium.com/djangotube/django-sqlite-to-postgresql-database-migration-e3c1f76711e1

housingsearch/templates/advice.html
<!DOCTYPE html>
{% extends 'base.html' %}{% load bootstrap5 %} {% bootstrap_css %} {%
bootstrap_javascript %} {%bootstrap_messages %} {% load socialaccount %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Advice page</title>
  </head>

  {% block content %}
  <body>
    <header class="masthead">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-10 mx-auto">
            <div class="site-heading" style="text-align: center">
              <h2 class="site-heading my-4 mt-3 text-white">
                Off-Grounds Housing Advice
              </h2>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div class="row card-header text-center">
      <div class = "col-md-3">
        Title
      </div>
      <div class = "col-md-6">
        Advice
      </div>
      <div class = "col-md-3">
        Date Posted
      </div>
    </div>
    <br />
    {% if advice_list %} {% for advice in advice_list %}
    <div class="row ">
      <div class = "col-md-3 text-center">
        <h5 style="padding: 5px"><b>{{ advice.title}}</b></h5>
      </div>
      <div class = "card col-md-6" style="background-color: rgb(233, 232, 232)">
        <p style="padding: 5px">{{advice.body}}</p>
      </div>
      <div class = "col-md-3 text-center">
        <p style="color: gray; padding: 5px">{{advice.created_on}}</p>      
      </div>
    </div>
    <hr />
    {% endfor %} {% else %}
    <p>No advice is available.</p>
    {% endif %}
    {% if user.is_authenticated %}
    <div style="text-align: center">
      <a
        href="{% url 'advice_post'%}"
        class="btn btn-primary"
        style="background-color: purple"
        >Add some advice for others looking for Off-Grounds Housing!</a
      >
    </div>
    {% endif %}
  </body>
  <style>
    body {
      font-size: 16px;
      background-color: #fcfcfc;
    }

    .head_text {
      color: white;
    }
    .masthead {
      background: purple;
      height: auto;
      padding-bottom: 1px;
      box-shadow: 0 16px 48px #e3e7eb;
      padding-top: 5px;
    }

    .card {
      box-shadow: 0 16px 48px #e3e7eb;
    }


  
  </style>

  {% endblock %}
</html>

housingsearch/templates/base.html
<!DOCTYPE html>

{% load bootstrap5 %} {% bootstrap_css %} {% load static %}
{%bootstrap_messages%} {% load socialaccount %} {% bootstrap_javascript %}

<html lang="en">
  {% if user.is_authenticated %}

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- <p class="navbar-brand"><b>Off Grounds Housing</b></p> -->
    <div class="card my-3"> <h5 class="card-header">Off Grounds Housing</h5></div>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'home' %}">Find a House</a>
        <a class="nav-item nav-link" href="{% url 'roommatefinder' %}"
          >Roommate Finder</a
        >
        <a class="nav-item nav-link" href="{% url 'map' %}">Map</a>
        <a class="nav-item nav-link" href="{% url 'advice' %}">Advice</a>
        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
      </div>
      <div
        class="collapse navbar-collapse justify-content-end"
        style="padding: 10px"
        id="navbarSupportedContent"
      >
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% else %}

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="card my-3"> <h5 class="card-header">Off Grounds Housing</h5></div>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'home' %}">Find a House</a>
        <!--      <a class="nav-item nav-link" href="{% url 'roommatefinder' %}">Roommate Finder</a>-->
        <a class="nav-item nav-link" href="{% url 'map' %}">Map</a>
        <a class="nav-item nav-link" href="{% url 'advice' %}">Advice</a>
      </div>
      <div
        class="collapse navbar-collapse justify-content-end"
        style="padding: 10px"
        id="navbarSupportedContent"
      >
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a
              class="nav-item nav-link"
              href="{% provider_login_url 'google' %}"
              >Log In</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endif %} {% block content %}

  <body>
    <style>
      body {
        font-size: 12px;
        background-color: #fdfdfd;
      }
      .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
      }
      .btn-danger {
        color: #fff;
        background-color: #2d8659;
        border-color: #26734d;
      }
      .masthead {
        background: purple;
        height: auto;
        padding-bottom: 1px;
        box-shadow: 0 16px 48px #e3e7eb;
        padding-top: 5px;
      }
    </style>

    <!-- Content Goes here -->
    {% endblock %}
  </body>

  <footer class="footer text-center text-md-start bg-light">
    <div class="container text-center p-4">
      <p>Copyright: B-17 University of Virginia</p>
    </div>
  </footer>
</html>

housingsearch/templates/detail.html
<!DOCTYPE html>

<html lang="en">
{% extends 'base.html' %}{% load bootstrap5 %}
    {% load socialaccount %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block content %}
  <head>
    <meta charset="UTF-8" />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.css' rel='stylesheet' />
    <title>Housing Detail</title>
  </head>


  <body onload="loadDirToLawn()">


    <legend style="color:white;background-color:purple;text-align:center;padding:15px"><h1>{{ housing.address }}</h1></legend>
    <br><br><br>
    <div class="row align-items-center">
      <div class="col-lg-5">
        <div class= "card offset-md-1 text-center border-dark rounded" style="border-style:solid">
       <h1 class="card-header" style="color:white;background-color:purple">Information </h1>
     <p class="display-6" >Rent: ${{ housing.rent }}</p>
      <hr class="style2">
      <p class="display-6">Bedrooms: {{ housing.bed }}</p>
      <hr class="style2">
      <p class="display-6">Bathrooms: {{ housing.bath }}</p>
      <hr class="style2">
      <p class="display-6">Square Feet: {{ housing.sqft }}</p>
      <hr class="style2">
        <p class="display-6" id="lawnDist">Distance to Lawn:</p>
        <hr class="style2">
      
<img src="{{housing.image.url}}" width="80%" height="80%" style="margin: 2em; text-align-center">
      
          </div>  
        </div>
      

    <div class="col-lg-6" id='map' style='width: 50%; height: 800px ;align-content: center;display: flex;margin-left: auto;
    margin-right: auto;'></div>
      </div>
    <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoiZ2F2aW4tZ3VvIiwiYSI6ImNrdm9iZXozaGN3MXoycHQ5am5vOTIzajMifQ.gycEz65lfHwNqvAqZPjQhA';
        var coordinate = []
    function CallRestService(request) {
        var script = document.createElement("script");
        script.setAttribute("type", "text/javascript");
        script.setAttribute("src", request);
        document.body.appendChild(script);
    }

    function DirectionCallBack(result){
        data = result
        console.log(data)
        document.getElementById("lawnDist").innerHTML = "Distance to Lawn: " + data.resourceSets[0].resources[0].routeLegs[0].travelDistance.toFixed(2) +  " miles"
        coords = data.resourceSets[0].resources[0].routeLegs[0].itineraryItems
        coords.forEach(c => coordinate.push(c.maneuverPoint.coordinates.reverse()));
        mapboxgl.accessToken = 'pk.eyJ1IjoiZ2F2aW4tZ3VvIiwiYSI6ImNrdm9iZXozaGN3MXoycHQ5am5vOTIzajMifQ.gycEz65lfHwNqvAqZPjQhA';
        const map = new mapboxgl.Map({
            container: 'map', // container ID
            style: 'mapbox://styles/mapbox/streets-v11', // style URL
            center: [-78.48, 38.03], // starting position [lng, lat]
            zoom: 9 // starting zoom
        });

        var marker = new mapboxgl.Marker()
        .setLngLat([ {{housing.long}}, {{housing.lat}} ])
        .setPopup(new mapboxgl.Popup().setHTML('<p><a href="{% url 'detail' housing.id %}">{{housing.address}}</a></p>'))
        .addTo(map);

        var marker2 = new mapboxgl.Marker({"color":"red"})
        .setLngLat([-78.5036,38.0352])
        .setPopup(new mapboxgl.Popup().setHTML('<p>The Lawn</p>'))
        .addTo(map);
        map.on('load', () => {
            map.addSource('route', {
                'type': 'geojson',
                    'data': {
                        'type': 'Feature',
                        'properties': {},
                        'geometry': {
                            'type': 'LineString',
                            'coordinates': coordinate
                        }
                     }
            });
            map.addLayer({
                'id': 'route',
                'type': 'line',
                'source': 'route',
                'layout': {
                    'line-join': 'round',
                    'line-cap': 'round'
                },
                'paint': {
                    'line-color': 'green',
                    'line-width': 8
                }
            });
        });
    }
    function loadDirToLawn(){
        CallRestService("https://dev.virtualearth.net/REST/V1/Routes?wp.0={{housing.lat}},{{housing.long}}&wp.1=38.0352,-78.5036&du=mi&jsonp=DirectionCallBack&key=AnWFVz7w1WQ49CscOkTj5JBoZICeQ4sipfPNoU2dRVWjNqiDOVYpJXMYeuykdYQk")
    }

    </script>
    <br><br><br><br><br>

    <div class="row">
        <legend style="color:white;background-color:purple;text-align:center;padding:15px"><h3>Review Section</h3></legend>
    <div class="col-sm-6">
    <form
      action="{% url 'rate' housing.id %}"
      method="post"

    >


      {% csrf_token %}
      <fieldset>


        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}

          {% if user.is_authenticated %}
          <legend style="text-align:center"><h2 class="display-5">Submit a Review!</h2></legend>
          {% else %}
          <legend style="text-align:center"><h2 class="display-5">Log in Before Review!</h2></legend>
          {% endif %}
          {% if user.is_authenticated %}

            {% for rating in housing.rating_set.all %}
              <div class="form-check offset-md-6">
                <input class="form-check-input"
                  type="radio"
                  name="choice"
                  id="rating{{ forloop.counter }}"
                  value="{{ rating.id }}"
                />
                <label class="form-check-label" for="rating{{ forloop.counter }}"
                  >{{ rating.rate_text }}
                </label>

</div>
            {% endfor %}


          {% endif %}

        
<br><br><br>
{% if user.is_authenticated %}
    <div class="offset-md-3 form-group">
            <label for="review" name="review">Review: </label>
            <input class="form-control form-control-lg" type="text" id="review" name="review"><br><br>
            <input type="submit" class="btn btn-primary" value="Rate and review!" />
    </div>
    {% endif %}
      </fieldset>

    </form>
    </div>
<div class="col-sm-6">
<!--        <div class="col-sm-6">-->
    <legend style="text-align:center">
            <h2 class="display-5">Reviews</h2>
            <p class="lead">Current Rating: {{average}}</p></legend>
             {% for review in housing.review_set.all %}
            <div class="card" style="width: 45rem;">

                  <div class="card-body">
                    <h5 class="card-title">{{review.name | title}}</h5>
                    <p class="card-subtitle mb-2 text-muted">{{review.created_at}}</p>
                    <p class="card-text">{{review.review_text}}</p>
                  </div>
            </div>
            <br>
<!--            <div class="text-center">{{review.name | title}} &#45;&#45; {{review.review_text}} &#45;&#45; {{review.created_at}}</div>-->
            {% endfor %}
<!--            <a href="{% url 'home' %}">HOME</a>-->
    </legend>
        </div>
    </div>




  </body>
<br><br><br><br>
{% endblock %}

housingsearch/templates/index.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-size: 16px;
        background-color: #fcfcfc;
    }
    
    .head_text {
        color: white;
    }
    .masthead {
          background: purple;
          height: auto;
          padding-bottom: 1px;
          box-shadow: 0 16px 48px #e3e7eb;
          padding-top: 5px;
        }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white ">Find a Roommate!</h3>
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author | title }} | {{ post.created_at}} </p>
                    <p class="card-text">{{post.content|slice:":400" }}</p>
                    <p class="card-text">Replies: ({{ post.comments.count }})  </p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary" style="background-color: purple">Reply &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} 
        {% endblock sidebar %}

    </div>
</div>


<!--<footer class="text-center text-md-start bg-light ">-->

<!--    <div class="text-center p-4">Copyright: B-17       University of Virginia</div>-->
<!--    </footer>-->

{% endblock %}